// +build !ignore_autogenerated

/*
Copyright 2021 CNCF.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialContainerCompletedStatus) DeepCopyInto(out *ConfidentialContainerCompletedStatus) {
	*out = *in
	if in.CompletedNodesList != nil {
		in, out := &in.CompletedNodesList, &out.CompletedNodesList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialContainerCompletedStatus.
func (in *ConfidentialContainerCompletedStatus) DeepCopy() *ConfidentialContainerCompletedStatus {
	if in == nil {
		return nil
	}
	out := new(ConfidentialContainerCompletedStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialContainersFailedNodeStatus) DeepCopyInto(out *ConfidentialContainersFailedNodeStatus) {
	*out = *in
	if in.FailedNodesList != nil {
		in, out := &in.FailedNodesList, &out.FailedNodesList
		*out = make([]FailedNodeStatus, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialContainersFailedNodeStatus.
func (in *ConfidentialContainersFailedNodeStatus) DeepCopy() *ConfidentialContainersFailedNodeStatus {
	if in == nil {
		return nil
	}
	out := new(ConfidentialContainersFailedNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialContainersInstallConfig) DeepCopyInto(out *ConfidentialContainersInstallConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialContainersInstallConfig.
func (in *ConfidentialContainersInstallConfig) DeepCopy() *ConfidentialContainersInstallConfig {
	if in == nil {
		return nil
	}
	out := new(ConfidentialContainersInstallConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialContainersInstallationInProgressStatus) DeepCopyInto(out *ConfidentialContainersInstallationInProgressStatus) {
	*out = *in
	if in.BinariesInstalledNodesList != nil {
		in, out := &in.BinariesInstalledNodesList, &out.BinariesInstalledNodesList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialContainersInstallationInProgressStatus.
func (in *ConfidentialContainersInstallationInProgressStatus) DeepCopy() *ConfidentialContainersInstallationInProgressStatus {
	if in == nil {
		return nil
	}
	out := new(ConfidentialContainersInstallationInProgressStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialContainersInstallationStatus) DeepCopyInto(out *ConfidentialContainersInstallationStatus) {
	*out = *in
	in.InProgress.DeepCopyInto(&out.InProgress)
	in.Completed.DeepCopyInto(&out.Completed)
	in.Failed.DeepCopyInto(&out.Failed)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialContainersInstallationStatus.
func (in *ConfidentialContainersInstallationStatus) DeepCopy() *ConfidentialContainersInstallationStatus {
	if in == nil {
		return nil
	}
	out := new(ConfidentialContainersInstallationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialContainersRuntime) DeepCopyInto(out *ConfidentialContainersRuntime) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialContainersRuntime.
func (in *ConfidentialContainersRuntime) DeepCopy() *ConfidentialContainersRuntime {
	if in == nil {
		return nil
	}
	out := new(ConfidentialContainersRuntime)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfidentialContainersRuntime) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialContainersRuntimeList) DeepCopyInto(out *ConfidentialContainersRuntimeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ConfidentialContainersRuntime, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialContainersRuntimeList.
func (in *ConfidentialContainersRuntimeList) DeepCopy() *ConfidentialContainersRuntimeList {
	if in == nil {
		return nil
	}
	out := new(ConfidentialContainersRuntimeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ConfidentialContainersRuntimeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialContainersRuntimeSpec) DeepCopyInto(out *ConfidentialContainersRuntimeSpec) {
	*out = *in
	if in.ConfidentialContainersNodeSelector != nil {
		in, out := &in.ConfidentialContainersNodeSelector, &out.ConfidentialContainersNodeSelector
		*out = new(v1.LabelSelector)
		(*in).DeepCopyInto(*out)
	}
	out.Config = in.Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialContainersRuntimeSpec.
func (in *ConfidentialContainersRuntimeSpec) DeepCopy() *ConfidentialContainersRuntimeSpec {
	if in == nil {
		return nil
	}
	out := new(ConfidentialContainersRuntimeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialContainersRuntimeStatus) DeepCopyInto(out *ConfidentialContainersRuntimeStatus) {
	*out = *in
	in.InstallationStatus.DeepCopyInto(&out.InstallationStatus)
	in.UnInstallationStatus.DeepCopyInto(&out.UnInstallationStatus)
	out.Upgradestatus = in.Upgradestatus
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialContainersRuntimeStatus.
func (in *ConfidentialContainersRuntimeStatus) DeepCopy() *ConfidentialContainersRuntimeStatus {
	if in == nil {
		return nil
	}
	out := new(ConfidentialContainersRuntimeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialContainersUnInstallationInProgressStatus) DeepCopyInto(out *ConfidentialContainersUnInstallationInProgressStatus) {
	*out = *in
	if in.BinariesUnInstalledNodesList != nil {
		in, out := &in.BinariesUnInstalledNodesList, &out.BinariesUnInstalledNodesList
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialContainersUnInstallationInProgressStatus.
func (in *ConfidentialContainersUnInstallationInProgressStatus) DeepCopy() *ConfidentialContainersUnInstallationInProgressStatus {
	if in == nil {
		return nil
	}
	out := new(ConfidentialContainersUnInstallationInProgressStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialContainersUnInstallationStatus) DeepCopyInto(out *ConfidentialContainersUnInstallationStatus) {
	*out = *in
	in.InProgress.DeepCopyInto(&out.InProgress)
	in.Completed.DeepCopyInto(&out.Completed)
	in.Failed.DeepCopyInto(&out.Failed)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialContainersUnInstallationStatus.
func (in *ConfidentialContainersUnInstallationStatus) DeepCopy() *ConfidentialContainersUnInstallationStatus {
	if in == nil {
		return nil
	}
	out := new(ConfidentialContainersUnInstallationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfidentialContainersUpgradeStatus) DeepCopyInto(out *ConfidentialContainersUpgradeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfidentialContainersUpgradeStatus.
func (in *ConfidentialContainersUpgradeStatus) DeepCopy() *ConfidentialContainersUpgradeStatus {
	if in == nil {
		return nil
	}
	out := new(ConfidentialContainersUpgradeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FailedNodeStatus) DeepCopyInto(out *FailedNodeStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FailedNodeStatus.
func (in *FailedNodeStatus) DeepCopy() *FailedNodeStatus {
	if in == nil {
		return nil
	}
	out := new(FailedNodeStatus)
	in.DeepCopyInto(out)
	return out
}
