name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Download controller-gen
      run: make controller-gen

    - name: Download kustomize
      run: make kustomize

    - name: Download envtest
      run: make envtest

    - name: Build controller
      run: make build
